name: Push EspNowNetwork to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove github actions
        run: rm -rf .github

      - name: Upload EspNowNetwork to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "EspNowNetwork"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
