name: Push EspNowNetwork to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove node and host idf folder
        run: rm -f EspNowNetworkNode EspNowNetworkHost

      - name: Remove arduino examples and library related files
        run: rm -f examples/arduino library.json library.properties

      - name: Remove github actions
        run: rm -f .github

      - name: Upload EspNowNetwork to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "EspNowNetwork"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
