name: Push EspNowNetworkHost to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove full
        run: rm -rf CMakeLists.txt idf_component.yml LICENSE

      - name: Move target
        run: mv EspNowNetworkHost/* ./

      - name: Remove sub IDF folders
        run: rm -rf EspNowNetworkNode EspNowNetworkHost EspNowNetworkHostDriver

      - name: Remove unused examples and sources
        run: rm -rf src/node host_driver examples/espidf/node examples/espidf/host_driver examples/arduino integration

      - name: Remove arduino
        run: rm -rf library.json library.properties

      - name: Remove github actions
        run: rm -rf .github

      - name: Replace ./.. with ./
        run: sed -i 's|./../|./|g' CMakeLists.txt

      - name: Upload EspNowNetwork to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "EspNowNetworkHost"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
