name: Push to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Upload EspNowNetwork to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          name: "EspNowNetwork"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}

      - uses: actions/checkout@v3.0.2
      - name: Upload EspNowNetworkHost to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          directories: EspNowNetworkHost
          name: "EspNowNetworkHost"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}

      - uses: actions/checkout@v3.0.2
      - name: Upload EspNowNetworkNode to component registry
        uses: espressif/github-actions/upload_components@master
        with:
          directories: EspNowNetworkNode
          name: "EspNowNetworkNode"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}