name: Push EspNowNetworkNode to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove full
        run: rm -rf CMakeLists.txt idf_component.yml LICENSE

      - name: Move node
        run: mv EspNowNetworkNode/* ./

      - name: Remove node and host idf folder
        run: rm -rf EspNowNetworkNode EspNowNetworkHost

      - name: Remove host code
        run: rm -rf src/host

      - name: Remove arduino examples and library related files
        run: rm -rf examples/arduino library.json library.properties

      - name: Remove github actions
        run: rm -rf .github

      - name: Replace ./.. with ./
        run: sed -i 's|./../|./|g' CMakeLists.txt

      - name: Upload EspNowNetwork to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "EspNowNetworkNode"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
