name: ESP-IDF CI
on: [workflow_call, push]
jobs:
  esp_idf_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - name: v443_build
            version_number: v4.4.3
            target: esp32c3
          - name: v512_build
            version_number: v5.1.2
            target: esp32c6
          - name: v520_build
            version_number: v5.2.0
            target: esp32c6
        path:
          - name: examples/espidf/host
          - name: examples/espidf/node
          - name: integration

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.version.version_number }}
          target: ${{ matrix.version.target }}
          path: ${{ matrix.path.name }}