name: ESP-IDF CI

on:
  workflow_call:
    inputs:
      target_path:
        type: string
        description: 'Path value to select a specific target in the matrix'
        required: true
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - name: v443_build
            version_number: v4.4.3
            target: esp32c3
          - name: v512_build
            version_number: v5.1.2
            target: esp32c6
          - name: v52_build
            version_number: v5.2.1
            target: esp32c6
        path:
          - name: examples/espidf/host
          - name: examples/espidf/node
          - name: examples/espidf/host_driver
          - name: integration/espidf

    steps:
      - if: github.event_name == 'workflow_call' && matrix.path.name != inputs.target_path
        run: exit 0

      - uses: actions/checkout@v4.1.1

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: ${{ matrix.version.version_number }}
          target: ${{ matrix.version.target }}
          path: ${{ matrix.path.name }}
