name: PlatformIO CI
on: [workflow_call, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - path: examples/arduino/host
            library: EspNowNetworkHost/library.json
            remove: "src/node"
          - path: examples/arduino/node
            library: EspNowNetworkNode/library.json
            remove: "src/host"
          - path: examples/arduino/host_driver
            library: EspNowNetworkHostDriver/library.json
            remove: "src/node"
          - path: integration/arduino
            library: ./library.json

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Copy src for host driver to src directly if example is host_driver
        run: mv host_driver ./src/
        if: ${{ matrix.example.path == 'examples/arduino/host_driver' }}

      - name: Remove files
        run: rm -rf ${{ matrix.example.remove }}
        if: ${{ matrix.example.remove }}

      - name: Copy library.json to root (if not src is also in root)
        run: mv ${{ matrix.example.library }} ./
        if: ${{ matrix.example.library != './library.json' }}

      - name: Build PlatformIO examples
        run: pio ci --lib="." --board=lolin_c3_mini --project-option="build_unflags = -std=gnu++11" --project-option="build_flags = -std=gnu++17" --project-option="platform=espressif32@6.4.0" --project-option="lib_ldf_mode=deep"
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example.path }}