name: PlatformIO CI

on:
  workflow_call:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - path: examples/arduino/host
            library: EspNowNetworkHost/library.json
            remove: "src/node src/host_driver"
            extra_dependencies: ""
          - path: examples/arduino/node
            library: EspNowNetworkNode/library.json
            remove: "src/host src/host_driver"
            extra_dependencies: ""
          - path: examples/arduino/host_driver
            library: EspNowNetworkHostDriver/library.json
            remove: "src/node"
            extra_dependencies: "johboh/MQTTRemote@^4.0.1, johboh/ConnectionHelper@^2.0.3"
          - path: integration/arduino
            library: ./library.json
            remove: "src/host_driver"
            extra_dependencies: ""

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Remove files
        run: rm -rf ${{ matrix.target.remove }}
        if: ${{ matrix.target.remove }}

      - name: Copy library.json to root (if not src is also in root)
        run: mv ${{ matrix.target.library }} ./ || true
        if: ${{ matrix.target.library != './library.json' }}

      - name: Build PlatformIO targets
        run: ${{ env.PLATFORMIO_CI_BASE }} --project-option="lib_deps=${{ matrix.target.extra_dependencies }}"
        env:
          PLATFORMIO_CI_BASE: >
            pio ci --lib="." --board=lolin_c3_mini
            --project-option="build_unflags=-std=gnu++11"
            --project-option="build_flags=-std=gnu++17"
            --project-option="platform=espressif32@6.4.0"
            --project-option="lib_ldf_mode=deep"
          PLATFORMIO_CI_SRC: ${{ matrix.target.path }}
