name: PR verification
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_espidf_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml

  build_platformio_examples_for_verification:
    uses: ./.github/workflows/platformio.yaml

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: 'src'
